### ISSUE TITLE
[Bug]-Search Engine not working - tube.instellate.xyz

### ISSUE THREAD

**Issue by davidd-bit** [lighttube-org/LightTube#168] opened 2024-09-13 15:40 UTC
### Describe the bug

LightTube instance this error occured on (tube.instellate.xyz)
LightTube & InnerTube versions (2024.8.15 / 2.0.0.18)
The full resource path (/results?search_query=allen+barton)
InnerTube language & region (en_JP)
The following text (the whole thing):
System.InvalidCastException: Unable to cast object of type 'InnerTube.Renderers.UnknownRendererData' to type 'InnerTube.Renderers.VideoRendererData'.
at AspNetCoreGeneratedDocument.Views_Shared_Renderers_ContainerRenderer.ExecuteAsync() in /src/LightTube/Views/Shared/Renderers/ContainerRenderer.cshtml:line 208
at AspNetCoreGeneratedDocument.Views_Shared_Renderers_SearchRenderer.ExecuteAsync() in /src/LightTube/Views/Shared/Renderers/SearchRenderer.cshtml:line 151
at AspNetCoreGeneratedDocument.Views_Youtube_Search.ExecuteAsync() in /src/LightTube/Views/Youtube/Search.cshtml:line 453
--- End of stack trace from previous location ---

### Notes

The search engine stopped working on 2024-09-06.
Also, similar errors to those posted above are occurring when trying to click on any saved subscription channel.

**Comment by kuylar** [comment] 2024-09-13 15:43
duplicate of lighttube-org/InnerTube#58, a fix is ready but there's some issues in the `poToken` feature, which needs a bit more testing. probably can push a fix by sunday (leaving this issue open until its merged

**Closed** 2024-09-14 17:12 UTC
Labels: bug
